- name: Create a user on TurnKey Linux via Webmin API
  hosts: turnkey
  vars:
    webmin_user: <WEBMIN_USER>
    webmin_password: <WEBMIN_PASSWORD>
    webmin_host: <WEBMIN_HOST>
    webmin_port: 12321
  tasks:
    - name: Login to Webmin (POST)
      ansible.builtin.uri:
        url: "https://{{ webmin_host }}:{{ webmin_port }}/session_login.cgi"
        method: POST
        validate_certs: false
        body: "user={{ webmin_user }}&pass={{ webmin_password }}"
        status_code:
          - 302
        headers:
          Cookie: "testing=1"
      register: login_response

    - name: Extract SID cookie
      ansible.builtin.set_fact:
        sid_cookie: "{{ login_response['set_cookie'] | regex_search('sid=([^;]+)', '\\1') | join }}"

    - name: Create user using session SID
      ansible.builtin.uri:
        url: "https://{{ webmin_host }}:{{ webmin_port }}/useradmin/save_user.cgi"
        method: POST
        validate_certs: false
        headers:
          Cookie: "sid={{ sid_cookie }}; redirect=1; testing=1"
          Content-Type: "text/plain;charset=UTF-8"
          Referer: "https://{{ webmin_host }}:{{ webmin_port }}/useradmin/edit_user.cgi?xnavigation=1"
        body: |
          "user=testUser&uid_def=1&uid=1000&real=&home_base=1&home=&shell=%2Fbin%2Fsh&passmode=1&pass=&encpass=&sshkey=&expired=&expirem=1&expirey=&min=&max=&warn=&inactive=&forcechange=0
           &newgid=&gidmode=0&gid=users&sgid=&makehome=1&copy_files=1&others=1"
        status_code: 302
...
