---
- name: Configure Repositories
  block:
    - name: Disable Enterprise Repositories
      ansible.builtin.lineinfile:
        path: "{{ item }}"
        regexp: '^(deb.*)'
        line: '#\1'
        backrefs: true
        state: present
      loop: "{{ enterprise_repos }}"

    - name: Enable No-Subscription Repositories
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list
        line: deb {{ no_subscription_repo }}
        insertafter: '^deb http://security\.debian\.org bookworm-security main contrib$'

- name: Update and Upgrade System
  block:
    - name: Run apt update
      ansible.builtin.apt:
        update_cache: true

    - name: Run apt dist upgrade
      ansible.builtin.apt:
        upgrade: dist

    - name: Install pip
      ansible.builtin.apt:
        name: python3-pip
        state: present

    - name: Install proxmoxer
      ansible.builtin.command: pip install proxmoxer --break-system-packages
      register: proxmoxer_result
      changed_when: "'Requirement already satisfied' not in proxmoxer_result['stdout']"

    - name: Update proxmox container templates
      ansible.builtin.command: pveam update
      changed_when: true
      register: pveam_update

- name: Enable IOMMU
  block:
    - name: Enable IOMMU for Intel CPUs
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT="((?!.*intel_iommu=on).*)"'
        line: 'GRUB_CMDLINE_LINUX_DEFAULT="\1 intel_iommu=on"'
        backrefs: true
        state: present
      when: "'GenuineIntel' in ansible_processor"

    - name: Enable IOMMU for AMD CPUs
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT="((?!.*amd_iommu=on).*)"'
        line: 'GRUB_CMDLINE_LINUX_DEFAULT="\1 amd_iommu=on"'
        backrefs: true
        state: present
      when: "'GenuineIntel' not in ansible_processor"

    - name: Update Grub
      ansible.builtin.command: update-grub
      changed_when: true

    - name: Reboot System
      ansible.builtin.reboot:

- name: Create ZFS Pools and Datasets
  block:
    - name: Create ZFS Pool - {{ zfs_pool_config['name'] }}
      community.general.zpool:
        name: "{{ zfs_pool_config['name'] }}"
        filesystem_properties:
          compression: "{{ zfs_pool_config['compression'] }}"
        vdevs:
          - type: "{{ zfs_pool_config['vdevs'][0]['type'] }}"
            disks: "{{ zfs_pool_config['vdevs'][0]['disks'] }}"

    - name: Create ZFS Dataset - {{ zfs_dataset_config['name'] }}
      community.general.zfs:
        name: "{{ zfs_dataset_config['name'] }}"
        state: present
...
